### PR TITLE
Create Ember app, port character concept gen

### PR DESCRIPTION
**Pull request by deverstalmage**
This PR creates a new [Ember.js](https://emberjs.com) app "Triune" and ports the Character Concept Generator to an Ember component. I plan on porting the generators to Ember components in order to ease maintenance burden and allow for easier collaboration/contribution.

To develop the app, navigate to the `app/static/triune` directory. Then, install the app's dependencies by running `yarn`. Once they are installed you can run `yarn ember s` to start the development server. The development server will watch the project files and will rebuild the app and reload the browser upon any changes.

My plan is to start with the less complex generators and work my way up to the more complicated ones like the monster generator.

### CODE REVIEW

**Comment by dicedatalore** [comment]
I like this very much, you are an absolute champion. I will get some time to view/merge it tomorrow

**Comment by deverstalmage** [comment]
Added some more (in progress) work on the settlement generator :+1:

**Comment by deverstalmage** [comment]
Finished off the settlement gen, added local storage support so content sticks around between refreshes

edit: I'll put any other enhancements into a different PR so this one doesn't continue to grow 😬

**Comment by deverstalmage** [comment]
going to close this for now, may revisit later!

**Pull request closed without merging**
